no1 = eval(input("choose a number---> "))
no2 = eval(input("choose another number ----> "))
ans1 = (no1 + no2)
ans2 = (no1 - no2)
ans3 = (no1 * no2)
ans4 = (no1 / no2)
ans5 = (no1 % no2)
ans6 = (no1 ** no2)
ans7 = (no1 // no2)

print("the sum of", no1 ,"and", no2 ,"is", ans1 ,)
print("the difference of", no1 ," and", no2 ,"is", ans2 ,)
print("the product of", no1 ,"and", no2 ,"is", ans3 ,)
print("the qoutient of", no1 ,"and", no2 ,"is", ans4 ,)
print("the remainder of", no1 ,"and", no2 ,"is", ans5 ,)
print("the exponent of", no1 ,"and", no2 ,"is", ans6 ,)
print("the floor division of", no1 ,"and", no2 ,"is", ans7 ,)